import { Asserts } from 'yup'
import { getPriceReqValidation } from './parkingPrice.schema'

export type TParkingPriceReqData = Asserts<typeof getPriceReqValidation>

// Generated by https://quicktype.io

export interface IParkinPriceResData {
  ticketStart: string
  ticketEnd: string
  creditBPKUsed: string
  creditBPKRemaining: string
  priceTotal: number
  priceWithoutDiscount: number
  priceBreakdown: PriceBreakdown[]
  cardInfo: CardInfo[]
}

export interface CardInfo {
  id: string
  cardSchemeGroupName: string
}

export interface PriceBreakdown {
  creditUsed: string
  price: number
  tariffIntervalDetail: TariffIntervalDetail
}

export interface TariffIntervalDetail {
  tariffStart: string
  tariffEnd: string
  timeInTariff: string
  tariffPrice: number
  parkingLimit: string
}
