import { Asserts } from 'yup'
import { getPriceReqValidation } from './parkingPrice.schema'
import { TTicketState } from '../pricing.d'

export type TParkingPriceReqData = Asserts<typeof getPriceReqValidation>

// Generated by https://quicktype.io

export interface IParkinPriceResData {
  created_at: string
  ecv: string
  employee: string
  extension: boolean
  id: string
  meta: Meta
  parent: string
  parking_end: string
  partner_id: string
  payment_id: string
  price: number
  state: TTicketState
  ticket_id_parksys: string
  udr: number
  updated_at: string
}

export interface Meta {
  ticketStart: string
  ticketEnd: string
  priceCard: number
  priceCash: number
}
