/*
 * File: card.schema.ts
 * Project: parking-native
 * Created Date: 29-11-2021
 * Author: Boris Nanista
 * -----
 * Last Modified: Mon Nov 29 2021
 * Modified By: Boris Nanista
 * ----------------------------------------------------------------------
 */

/**
 * Operation identifier. CP for payment, CC for cancel, CR for refund
 */
export type TOperation = 'CP' | 'CC' | 'CR'

export interface ICardPaymentReq {
  externalId?: string
  requestContents?: RequestContents
  printCustomerReceipt?: boolean
  printMerchantReceipt?: boolean
}

export interface RequestContents {
  operation?: TOperation
  amount?: string
  transactionId?: string
  hostTransId?: string
}

// Generated by https://quicktype.io

export enum EPaymentResult {
  SUCCESS = '0',
  CANCELED = '1',
  /** unspecified errors */
  ERROR_2 = '2',
  ERROR_3 = '3',
  ERROR_4 = '4',
  ERROR_5 = '5',
  ERROR_6 = '6',
  ERROR_7 = '7',
  ERROR_8 = '8',
  ERROR_9 = '9',
}

export type TPaymentResult = `${EPaymentResult}`

export interface ICardPaymentRes {
  content: {
    [key: string]: string
    result: TPaymentResult
    customerReceipt: string
    merchantReceipt: string
  }
  status: Status
  success: boolean
}

export interface Status {
  code: number
}
