// Generated by https://quicktype.io

export interface udrInfo {
  id: number
  mestskaCast: MestskaCast
  kodZony: KodZony
  nazov: string
  maxParkovanie: string
  bezpPark: string
  obmedzenePreApk: string
  vynimkaZoSpoplatnenia: VynimkaZoSpoplatnenia
  vynimkaApk: string
  udrid: string
  globalIdString: string
  shapeArea: string
  shapeLength: string
  vyhradene: Vyhradene
}

export enum KodZony {
  Nm1 = 'NM1',
  Pe1 = 'PE1',
  Ra1 = 'RA1',
}

export enum MestskaCast {
  NoveMesto = 'Nové Mesto',
  Petrzalka = 'Petržalka',
  Raca = 'Rača',
}

export enum Vyhradene {
  Verejne = 'verejné',
}

export enum VynimkaZoSpoplatnenia {
  The024 = '0-24',
}

export type TudrResData = udrInfo[]
