// Generated by https://quicktype.io

export interface IUdrInfo {
  mestskaCast: string
  kodZony: string
  nazov: string
  udrid: string
}

//left commented properties in case we need them in future
export interface IUdrFeaturesInfo {
  properties: {
    // OBJECTID: number // 2
    'Mestská časť': string // "Nové Mesto"
    'Kód rezidentskej zóny': string // "NM1"
    Názov: string // "Jiskrova + Belehradská"
    // 'Časové obmedzenie dĺžky parkovania (min)': number // 0
    // 'Úvodný bezplatný čas parkovania (min)': number // 0
    // 'Obmedzené len pre RPK, APK': string // "N/A"
    // 'Výnimka zo spoplatnenia (RPK, APK)': string // "0-24"
    // 'Výnimka z obmedzenia dĺžky parkovania (RPK, APK)': string // "N/A"
    'UDR ID': number // 3101
    // 'Vyhradené parkovacie státie (sk)': string // "verejné"
    // GlobalID: string // "7cde9a70-0018-4074-b1ac-390f6e6767e0"
    // GlobalID_A: string // "{1DFADE72-2D43-4B25-BCF8-D93C4A420151}"
    // Obvod: number // 663.67564614531
    // Plocha: number // 5041.11415570715
    Status: string //'active', 'planned'
    // 'ODP Platnosť RPK a APK': string //'NM1, SM1'
    // web: string // 'ano'
    // 'export partneri': string // 'ano'
    // 'Informácia RPK (sk)': string // null
    // 'Informácia NPK (sk)': string // null
    // 'Informácia RPK (en)': string // null
    // 'Informácia NPK (en)': string // null
    // 'Vyhradené parkovacie státie (en)': string //'public'
    // 'Čas spoplatnenia (sk)': string //'pracovné dni 8-24'
    // 'Čas spoplatnenia (en)': string //'workdays 8-24'
    // 'Cena (eur/h)': number //1.5
    // 'Doplnková informácia (sk)': string // null
    // 'Doplnková informácia (en)': string // null
    // 'Víkendy a sviatky': string // null
  }
}

// other types left commented if needed in future
export interface IUdrsOnlineInfo {
  features: IUdrFeaturesInfo[]
}
