// Generated by https://quicktype.io

export interface IUdrInfo {
  id: number
  mestskaCast: string
  kodZony: string
  nazov: string
  maxParkovanie: string
  bezpPark: string
  obmedzenePreApk: string
  vynimkaZoSpoplatnenia: string
  vynimkaApk: string
  udrid: string
  globalIdString: string
  shapeArea: string
  shapeLength: string
  vyhradene: string
}

export type TudrResData = IUdrInfo[]
